### ISSUE TITLE
Misleading stats from laziness

### ISSUE THREAD

**Issue by neverfox** [ptaoussanis/tufte#15]
While profiling a collection of functions, it appears that all of the time gets attributed to the function that causes a lazy collection to be realized rather than the function that actually "does" the heavy lifting, leading on to misattribute the source of the problem. For example:

```
(defnp fast-fn [coll]
  (count coll))

(defnp slow-fn []
  (mapcat (fn [i] (map (fn [j] (+ i j)) (range 10000))) (range 10000)))
```

```
user> (profile {} (-> (slow-fn) fast-fn))
100000000

pId      nCalls       Min        Max       MAD      Mean   Time% Time
::defn_fast-fn           1    10.13s     10.13s       0ns    10.13s     100 10.13s
::defn_slow-fn           1  392.25μs   392.25μs       0ns  392.25μs       0 392.25μs
Clock Time                                                          100 10.13s
Accounted Time                                                          100 10.13s
```

I'm not sure there's a way to avoid this as it is, from one perspective accurate, but I'm just not sure if it's going to be the most useful perspective a lot of the time. Do you know of any way to have the profiler put the blame where it's due?

**Comment by ptaoussanis** [comment]
Hi Roman,

This relates to #14, will add a short mention re: laziness to the `profile/d` docstrings in a moment.

Short answer: all forms of laziness can+will only be counted toward active profiling if/when realisation occurs. That's an intentional and important property.

A common confusion I observe in Clojure is that folks often reach for laziness (intentionally or unintentionally) when they either don't specifically need it, or even especially want it. I believe this often happens due to historical reasons: early Clojure books/posts/idioms often encouraged reaching for laziness by default.

In practice, this can often leads to confusion (e.g. re: when evaluation happens, chunking, binding conveyance, unexpected influences on logging , etc.) - and can also often incur unwanted overhead. Actually needing/wanting laziness is fairly rare IME, and mostly reserved to cases of infinite sequences.

Anyway, to answer your question: the solution I'd like to suggest is to encourage folks to try become more aware of where laziness might lie in their systems and when (and under what conditions) that laziness gets (or should get) realised in practice.

This may seem like a non-answer, but it's I believe it's the only correct one. When do you need/want certain laziness to be realised/evaluated? There'll normally be some specific place or scope where that makes sense for your application. You can profile there (with explicit realisation) if you'd like your profiling to include realisation costs.

In your specific example: `slow-fn` is lazy. If that's indeed intentional, then presumably you'll have some place where its result will actually be evaluated for some given input- that'd be a reasonable place to profile in production.

If you literally just want to profile this form at the REPL, just wrap with `dorun` or something similar.

Hope that helps a little? Cheers! :-)
