### ISSUE TITLE
add-basic-spit-handler! (?)

### ISSUE THREAD

**Issue by evalapply** [ptaoussanis/tufte#18]
Hello,

Would it make sense to have `add-basic-spit-handler!` in tufte? If so, I could send you a PR maybe?

I just discovered tufte. I have an application which communicates through stdout. I need to see the profiling results in a file and never in the stdout. I don't think reusing `add-basic-println-handle!` for this purpose is possible and copying these 12 lines of code to my project just to replace `println` with `spit` feels wrong.  I also tried using `add-timbre-logging-handler!` which required adding timbre to project dependencies and new requirements in files ( `taoensso.tufte.timbre`, `taoensso.timbre` and `taoensso.timbre.appenders.core`, the last one for the `spit-appender`). After adding `spit-appender` to the timbre config I had to disable the other appender, the one printing to stdout, so this solution is just overkill for something I almost have out of the box. Am I missing something obvious?

**Comment by ptaoussanis** [comment]
Hi Łukasz,

Thanks for pinging about this. So the trouble is deciding where to draw the line :-)

A spit appender in-the-box sounds quite reasonable. But then someone will (also quite reasonably) ask for a small feature to auto-create missing dirs in the spit path. Or to control the spit options. Or possibly a mechanism to hold the file open to prevent needing to open+close too often? And if we have a println and spit appender out the box, why not simple file rotation?

Anyway, my point is that there's no obvious set of small universal functionality that we can choose that'll cover as the 80% case since everyone's idea of 80% seems to be a little different :-)

Instead, I'd like to encourage folks to feel comfortable with just using their own function for appending since this approach is:

1. Flexible (you can fully control all behaviour, including formatting).
2. Transparent (no unexpected behaviour hidden in a lib author's own function somewhere).
3. In keeping with Clojure's general principles of not shying away from anonymous / 1-use fns when they present a good tradeoff.

Wouldn't recommend Timbre in your case if you're literally only going to use it for Tufte output. Instead, this seems quite reasonable to me (and again, has the benefits of transparency and flexibility to counteract any aesthetic concerns):

```clojure
(add-handler! :my-appender "*"
  (fn [m]
    (let [{:keys [stats-str_ ?id ?data]} m
          stats-str (force stats-str_)]
      (spit my-file
        (str
          (when ?id   (str "\nid: "   ?id))
          (when ?data (str "\ndata: " ?data))
          "\n" stats-str)))))
```

I do honestly understand why this may not feel right, but experience with Timbre has shown that if you give people too many config options - they're sometimes irrationally inclined to spend hours trying to coerce/fight the config defaults rather than taking 2 minutes to just write a little inline function that does exactly what they want.

So I'm now in the habit of trying to encourage folks to instead see _functions_ as the atomic unit of configuration - if that makes sense? You just can't beat a function for flexibility or transparency.

**Comment by evalapply** [comment]
Functions as atomic units of configuration. Yes, that makes sense. Power to programmers! Thanks for an elaborated answer.
I guess it proves your point that I ended with something like this (timestamps and appending):
```clojure
(add-handler! :my-appender "*"
  (fn [m]
    (let [{:keys [stats-str_ ?id ?data]} m
          stats-str (force stats-str_)]
      (spit my-file
        (str
         "\n\n"
         (java.util.Date.)
         (when ?id   (str "\nid: "   ?id))
         (when ?data (str "\ndata: " ?data))
         "\n" stats-str) :append true)))))
```
I leave it here, because 80% of people writing spitting handlers will need appending and timestamps ;-)

**Comment by ptaoussanis** [comment]
No problem!

> I guess it proves your point that I ended with something like this (timestamps and appending):

:-) You can also see the `add-handler!` docstring for info on other keys in `m` that you might want to consider using (namespace, level, etc.)

Cheers!
