### ISSUE TITLE
No output at all

### ISSUE THREAD

**Issue by saulshanabrook** [ptaoussanis/tufte#20]
I am having trouble getting this to output anything at all. I am sure there is something very obvious I am missing. I [created an example repo](https://github.com/saulshanabrook/tufte-example), that just contains your example from the README. However, when I run it, it produces no output.

This is the file in the repo:

```clojure
(ns example)

(require '[taoensso.tufte :as tufte :refer (defnp p profiled profile)])

;; We'll request to send `profile` stats to `println`:
(tufte/add-basic-println-handler! {})

;;; Let's define a couple dummy fns to simulate doing some expensive work
(defn get-x [] (Thread/sleep 500)             "x val")
(defn get-y [] (Thread/sleep (rand-int 1000)) "y val")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; main function

(defn -main 
  [& args]
  (profile ; Profile any `p` forms called during body execution
    {} ; Profiling options; we'll use the defaults for now
    (dotimes [_ 5]
      (p :get-x (get-x))
      (p :get-y (get-y)))))
```

Any ideas?

**Comment by alexandergunnarson** [comment]
Getting the same issue, but only in certain environments. Not yet sure what the issue is, because the local environment prints just fine, but the remote (SSH) environment doesn't. `println` and friends work, as does `tufte/profiled`, but `tufte/profile` does not.

**Comment by ptaoussanis** [comment]
Hey all, sorry for the delay replying!

So the basic println handler uses `println`, but  [on a dedicated handler thread](https://github.com/ptaoussanis/tufte/blob/13756bd20f8eab1009913b31cc3e53f9999b63a0/src/taoensso/tufte/impl.cljc#L189) (to ensure that calls aren't blocking).

Depending on your environment, `*out*` may be bound differently off the main or REPL thread.

The [basic println handler itself](https://github.com/ptaoussanis/tufte/blob/13756bd20f8eab1009913b31cc3e53f9999b63a0/src/taoensso/tufte.cljc#L217) is pretty simple, so you could experiment with writing your own custom handler fn that uses an explicit value for `*out*`, cutting some of the potential complexity.

Otherwise you might just want to explore what `*out*` is actually bound to for background threads in your particular environment/s.

Hope that helps / makes sense?

**Comment by saulshanabrook** [comment]
@ptaoussanis Ah, I see! That makes a lot of sense.  Is there anyway to not use another thread?

**Comment by ptaoussanis** [comment]
No way out-the-box but you could use `profiled` instead of `profile`, then manually trigger a handler (or write a function which does this).

Would caution that the reason for doing the handling on another thread is to make sure that the cost of handling doesn't impact execution - something that _could_ be a concern depending on context.

**Comment by saulshanabrook** [comment]
Sounds good. Thank you for your time explaining this. I am gonna close this issues since it seems like you can fix this problem by:

* Making a new println handler that makes sure it using the right value bound for `*out*
* Use `profiled` and then print the data manually
