### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by emlyn** [ptaoussanis/tufte#29]
I tried the example code from the README, slightly modified as follows:
```clojure
(ns trial
  (:require [taoensso.tufte :as tufte :refer (p profiled profile)]))

;;; Let's define a couple dummy fns to simulate doing some expensive work
(defn get-x [] (Thread/sleep 500)             "x val")
(defn get-y [] (Thread/sleep (rand-int 1000)) "y val")

(defn -main []
  ;; We'll request to send `profile` stats to `println`:
  (tufte/add-basic-println-handler! {})


  ;; How do these fns perform? Let's check:
  (profile ; Profile any `p` forms called during body execution
   {} ; Profiling options; we'll use the defaults for now
   (dotimes [_ 5]
     (p :get-x (get-x))
     (p :get-y (get-y)))))
```
But when I run it (`lein run -m trial`), nothing at all is printed out.
I tried changing the `profile` call to `profiled` and wrapping it in a call to `prn` and it outputs:
```
[nil #object[taoensso.tufte.impl.PStats 0xc247363 {:status :pending, :val nil}]]
```
I must be missing something... have you got any pointers to what I'm doing wrong?

Thanks in advance for any help.

**Comment by ptaoussanis** [comment]
Hi Emlyn,

Not sure why you're not seeing output with the default `println` handler- could be that your std-out is being captured somewhere.

> I tried changing the profile call to profiled [...]

That's a good idea. You'll need to deref the second element (PStats) here though to see something useful. Please see the `profiled` docstring for more info.

If you're using `profiled` instead of `profile`, you may also want to look at `format-pstats` to get tabular output as shown in the README example.

Hope that helps!

**Comment by emlyn** [comment]
Thanks, with `profiled` and `format-pstats` I can get it working.
I've made a minimal project [here](https://github.com/emlyn/tufte-trial) that uses `profile` and doesn't print anything for me, it would be interesting to see if it works for others or not.
