### ISSUE TITLE
merge-pstats assumes stats are always overlapping in time

### ISSUE THREAD

**Issue by ivarref** [ptaoussanis/tufte#35]
Hi, and thanks once again for a great library.

It seems that `merge-pstats` assumes that its inputs are always overlapping in time.
For example:

```clojure
(test/deftest merge-discrete-events
  (test/testing "Merge discrete events"
    (let [[_ ps0] (profiled {} (p :foo "foo"))
          _ (Thread/sleep 100) ; Majority of time spent outside of profiling
          [_ ps1] (profiled {} (p :foo "foo"))
          merged @(tufte/merge-pstats ps0 ps1)]
      (pprint/pprint merged)
      (is (< (get-in merged [:clock :total]) 1e8))))) ; Fails
```

This test will fail and print:
```clojure
{:clock {:t0 2109412625335, :t1 2109513733727, :total 101108392},
;                                                     ^^^ Incorrect total, includes (Thread/sleep 100)
 :stats
 {:foo
  {:min 181,
   :mean 501.0,
   :mad-sum 640.0,
   :p99 821,
   :n 2,
   :p90 821,
   :max 821,
   :mad 320.0,
   :p50 821,
   :sum 1002,
   :p95 821}}}
```

I hit this error while trying to write a simple aggregate handler. I suppose that in nested cases of `profiled` it makes sense to assume overlapping, but not when you have multiple discrete events. I'm not quite sure how to solve this correctly. Or am I doing something wrong?

Regards.

**Comment by ivarref** [comment]
I've implemented a (likely) lossy strategy in the referenced commit.

**Comment by ivarref** [comment]
And now with a mostly non-lossy strategy. That is: After compacting loss may occur.

**Comment by ptaoussanis** [comment]
Hi @ivarref,

Thanks for prompting about this.

It's a nice solution, and certainly flexible- but I'm hesitant to incur the time-span sort cost for merges.

Didn't have much time to think about or discuss this (only had an afternoon for open source)- but as one possible alternative, I quickly implemented [this](https://github.com/ptaoussanis/tufte/commit/dbd75e7961fbdefcfd91d37ddb286c90411b4b0e). Basically: time intervals will be merged accurately (at insignf. additional cost) when they happen to be in order, and approximated otherwise.

This way we support 3 cases:
  - Users who don't care about clock accuracy never have to pay for sorting.
  - Users who are using a serialization mechanism get clock accuracy for free [1].
  - Otherwise users can choose to manually pre-sort their PStats before merging.

[1] I'm curious to see how this goes in practice. We may actually want to relax the inequality [here](https://github.com/ptaoussanis/tufte/commit/dbd75e7961fbdefcfd91d37ddb286c90411b4b0e#diff-bef38f16add2e64baaea36e5552f5ef3R192) to allow for some minor order noise due to contention while queuing.

I also expanded the existing [accumulator utils](https://github.com/ptaoussanis/tufte/commit/1a1aaaf6603757ec413fe435be1d896ce2c65727) and added some extra documentation to hopefully make it clearer how they can be used. Please ping if these still don't cover your use case.

Finally, I collected together your [formatting enhancements](https://github.com/ptaoussanis/tufte/commit/3c0f741435e9f27dbb01350ce30d097d33afb1c5) and took the liberty to refactor the options a little since it looks quite likely we'll add more options in future.

I've just pushed all changes to [[com.taoensso/tufte "2.1.0-RC2"]](https://github.com/ptaoussanis/tufte/blob/master/CHANGELOG.md) on Clojars.

Did this in a rush, please forgive the branch noise- and please ping if I missed anything (very possible).

**Comment by ivarref** [comment]
Thanks for a thorough review and pragmatic solution @ptaoussanis . It sounds like a good solution to me.

The new accumulator utils also looks good. Thanks.

I'll try to document the formatting options in the near feature.
