### ISSUE TITLE
ConcurrentModificationException in `stats-accumulator` (thrown from `merge-pstats`)

### ISSUE THREAD

**Issue by matthewdowney** [ptaoussanis/tufte#61]
Hey there! Thanks for all of the great software. 

I have a Clojure application that I control from the REPL, and I'm using two handlers for tufte data. One is a stats accumulator (via `add-accumulating-handler!`) that I'm draining every minute into a database, and the second is a stats accumulator that I'm managing manually with `stats-accumulator` and core.async, which I'm draining every 15 minutes and logging with timbre. 

The second one is throwing a `ConcurrentModificationException` every so often (probably once every 5 hours under heavy use) and I'm curious what I might be doing wrong. The `add-accumulating-handler!` implementation would swallow the error and continue I think (since the agent's :error-mode is :continue) so I'm not totally sure that this error is specific to my implementation.

Anyway, in my REPL namespace I have the following:

```clojure
(require '[taoensso.timbre :as timbre])
(require '[taoensso.encore :as enc])
(require '[taoensso.tufte :as tufte])
(require '[clojure.core.async :as async])

;; mostly for exceptions thrown on core.async threads
(Thread/setDefaultUncaughtExceptionHandler
  (reify Thread$UncaughtExceptionHandler
    (uncaughtException [_ thread ex]
      (timbre/error ex "Uncaught exception on" (.getName thread)))))

(defonce repl-stats
  (let [stats (tufte/stats-accumulator)
        buf (async/chan 1024)]
    
    ;; queue stats for consumption
    (tufte/add-handler! :repl-pstats "*" #(async/>!! buf %))

    (async/go-loop [next-timeout (async/timeout (enc/ms :mins 15))]
      (async/alt!
        buf ;; consume stats from the buffer and invoke the accumulator
        ([datum]
         (when-let [{:keys [?id pstats]} datum]
           (stats (or ?id :tufte/nil-id) pstats) ;; <-- this throws sometimes
           (recur next-timeout)))

        next-timeout ;; periodically drain & log the stats
        ([_]
         (timbre/info (tufte/format-grouped-pstats @stats))
         (recur (async/timeout (enc/ms :mins 15))))))

    stats))    
```

Eventually, I'll see that there was an uncaught exception from the async thread when invoking `stats`:

```
2020-10-24T22:31:50.719Z ERROR [the-system.data.collector:499] - Uncaught exception on async-dispatch-5
                                              java.lang.Thread.run              Thread.java:  834
                java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  628
                 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1128
                                                               ...
          clojure.core.async.impl.channels.ManyToManyChannel/fn/fn             channels.clj:   95
                                  clojure.core.async/do-alts/fn/fn                async.clj:  252
                                   clojure.core.async/ioc-alts!/fn                async.clj:  383
      clojure.core.async.impl.ioc-macros/run-state-machine-wrapped           ioc_macros.clj:  977
              clojure.core.async.impl.ioc-macros/run-state-machine           ioc_macros.clj:  973
   the-system.data.collector/eval42802/fn/fn/state-machine--auto--            collector.clj:  417
the-system.data.collector/eval42802/fn/fn/state-machine--auto--/fn            collector.clj:  417
                                  /taoensso.tufte.StatsAccumulator               tufte.cljc:  715
                                          taoensso.tufte/sacc-add!               tufte.cljc:  711
                                                clojure.core/swap!                 core.clj: 2352
                                                               ...
                                       taoensso.tufte/sacc-add!/fn               tufte.cljc:  711
                                  taoensso.tufte.impl/merge-pstats                impl.cljc:  229
                                  taoensso.tufte.impl/merge-pstats                impl.cljc:  252
                           taoensso.tufte.impl/times-into-id-times                impl.cljc:  181
                                               clojure.core/reduce                 core.clj: 6828
                                       clojure.core.protocols/fn/G            protocols.clj:   13
                                         clojure.core.protocols/fn            protocols.clj:   75
                                clojure.core.protocols/iter-reduce            protocols.clj:   49
                                 java.util.LinkedList$ListItr.next          LinkedList.java:  892
               java.util.LinkedList$ListItr.checkForComodification          LinkedList.java:  970
java.util.ConcurrentModificationException:
```

Is there something that you see me obviously doing wrong? I tried to reproduce the error by reducing the interval from 15 minutes to one second and just hammering on calls to `profile` from different threads, but no luck.

**Comment by ptaoussanis** [comment]
@matthewdowney Hi Matthew, thanks for the clear + detailed report, that's very helpful.

Based on a quick skim here, nothing obviously wrong you're doing - I suspect there's a bug. Will try check this out in more detail next weekend. In the meantime you can probably work around this by using `{:dynamic? true}` for your profile calls.

This'll skip the use of mutable state.

**Comment by matthewdowney** [comment]
Sure, thanks for the quick response. If I manage to reproduce it more reliably I'll try to debug.

**Comment by ptaoussanis** [comment]
Quick update to mention that it occurred to me what the bug likely is. No need for further debugging from your end, thanks! Will try get this fixed next week/end.

**Comment by matthewdowney** [comment]
Oh hey, one more update here that might end up being related: I've also just seen an `EmptyStackException` from `pdata-proxy-pop`. 

This one is interesting because I'm wrapping a call to `async/>!` in `profile`, which is maybe not advisable. The code I have is something along the lines of this:

```clojure
(let [in (comment "a core.async chan")
      out (comment "another core.async chan")
      max-batch-size 5000]

  ;; Consume msgs from `in`, writing batches to `out` when either one second
  ;; passes or when a batch reaches `max-batch-size`
  (async/go-loop [batch []
                  batch-timeout (async/timeout 1000)]
    (async/alt!
      in
      ([msg]
       (tufte/profile {:id :round-trip} ;; <-- this throws occasionally
         
         ;; cature round trip time for the message
         (tufte/capture-time! (:type msg) (- (System/nanoTime) (:ts msg)))
         
         ;; either update the batch & recur, or flush it if it's too large
         (let [batch (conj batch msg)]
           (if (= (count batch) max-batch-size)
             (do
               (async/>! out batch)
               (recur [] (async/timeout 1000)))
             (recur batch batch-timeout)))))
      
      batch-timeout
      ([_]
       (when (seq batch)
         (async/>! out batch))
       (recur [] (async/timeout 1000))))))
```

and the stack trace I'm getting is this:


```
2020-10-26T00:51:00.659Z ip-172-31-26-180 ERROR [the-system.data.collector:481] - Uncaught exception on async-dispatch-5
                                              java.lang.Thread.run              Thread.java:  834
                java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  628
                 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1128
                                                               ...
          clojure.core.async.impl.channels.ManyToManyChannel/fn/fn             channels.clj:   95
                                  clojure.core.async/do-alts/fn/fn                async.clj:  252
                                   clojure.core.async/ioc-alts!/fn                async.clj:  383
      clojure.core.async.impl.ioc-macros/run-state-machine-wrapped           ioc_macros.clj:  977
              clojure.core.async.impl.ioc-macros/run-state-machine           ioc_macros.clj:  973
   the-system.data.influx/write-to-influx/fn/state-machine--auto--               influx.clj:  172
the-system.data.influx/write-to-influx/fn/state-machine--auto--/fn               influx.clj:  172
                     taoensso.tufte.impl/eval13131/pdata-proxy-pop                impl.cljc:   88
                                               java.util.Stack.pop               Stack.java:   84
                                              java.util.Stack.peek               Stack.java:  102
java.util.EmptyStackException:
```

It seems unrelated, but I thought I'd put it here just in case. 

Cheers!

**Comment by ptaoussanis** [comment]
Okay, just took a quick look at the code and am less confident now that this is actually a bug. Would suggest please aiming again for a minimal reproducible example.

Let me explain first a little what's actually going on.

- `(profile/d {:dynamic? false} ...)` sets up some mutable state that is **not** thread safe, and to which any wrapped `p` calls will have their runtimes captured.

- When `profile/d` completes, it returns a `PStats` object, which includes this mutable state. No one should still be mutating the state at this point (capturing runtimes), so the mutability shouldn't be an issue.

- Dereffing the `PStats` object will iterate over the mutable state and produce+cache a prepared output.

So far so good.

- A "stats accumulator" (`sacc`) is just an atom of `{<group-id> <PStats>}`. 
- Calls to a `sacc` just merge a new `<PStats>` into a pre-existing `<PStats>` using `impl/merge-pstats`.
- Calls to a `sacc` involve iterating over a mutable accumulator, so it's important that both `PStats` involved in merging are not still actively being mutated.

The above all lead to a few conditions which need to always hold when `{:dynamic? false}`:

- `capture-time!` must never be called against the same mutable state (`PData`) from >1 concurrent thread.
- `capture-time!` must never be called after the relevant `profile/d` body has ended.
- `sacc` must never been invoked against a `PStats` that is still being mutated (e.g. to which times are still being captured).
- `sacc` should ideally not be invoked from >1 concurrent thread, since this could lead to merge contention and so wasted work (merge retries).

Is it possible that any of the above invariants are being violated in your project?

Regarding your `EmptyStackException`: I suspect that this is coming from concurrent execution [here](https://github.com/ptaoussanis/tufte/blob/6f631a3b058b745d63915f94c8bd9c351d99dc09/src/taoensso/tufte/impl.cljc#L88) between the `(.empty stack)` and `(.pop stack)`.

Which seems to imply that you somehow have >1 concurrent thread calling `pdata-proxy-pop` on the same `PData` (i.e. against the same mutable context). I.e. could be the same underlying cause as the `ConcurrentModifiedException`.

Your `(async/>! out batch)` call will park if `out` buffer is full - is it possible this is happening? In this case I guess it's possible that the `go` call is starting with `Thread x`, parking, then resuming with `Thread y` and Tufte's local thread state is getting messed up.

A recommendation to help prevent such issues: don't call `(profile/d {:dynamic? false} ...)` inside a go block. You need to ensure that the `profile/d` call starts and finishes on the same thread w/o interruption.

One way you can do this is to pull the logic you want to profile into a fn _outside_ of the go block. Anyway I'd recommend leaving as little logic as possible within `go` blocks for general hygiene. They're a source of confusion and often bugs (since the `go` macro is quite complex). I'd recommend using `go` blocks for minimal un/parking logic, then immediately call into fns when you have what you need.

In this case that'd help you realise that you can't have a call to `async/>!` wrapped in `profile/d`.

I'll adjust the docs to include this recommendation.

Does this help / make sense?

**Comment by matthewdowney** [comment]
> Which seems to imply that you somehow have >1 concurrent thread calling pdata-proxy-pop on the same PData (i.e. against the same mutable context). I.e. could be the same underlying cause as the ConcurrentModifiedException.

> Your (async/>! out batch) call will park if out buffer is full - is it possible this is happening? In this case I guess it's possible that the go call is starting with Thread x, parking, then resuming with Thread y and Tufte's local thread state is getting messed up.

This is exactly what's happening. Thank you so much for your time spent here and for the detailed explanation of the thread safety semantics — crystal clear. (The new docstrings as well.) You can probably close this issue as a case of user error. :)

**Comment by ptaoussanis** [comment]
@matthewdowney Awesome, happy to hear that it looks like we've pinned down the cause 👍 

Was also a good opportunity to improve the docstrings. Thanks again for the clear+friendly issue. Feel free to re-open if you run into any more trouble.
