### ISSUE TITLE
Nested `p`'s are not taken into consideration when calculating percentages.

### ISSUE THREAD

**Issue by j-pb** [ptaoussanis/tufte#7]
Currently, the time spend percentage of `format-stats` doesn't take into account nested `p` forms, so `(p :a (p :b ...))` will state that both `:a` and `:b` spend 50% of the time.

**Comment by ptaoussanis** [comment]
Hi there, that's the expected behaviour and a useful property.

The `p` contract is: time the form. If the form happens to include additional nested timed forms, that's incidental and doesn't affect the outside time. Trying to do that would quickly become confusing.

That A's time depends on B's time is something you'll often want to measure and quantify.

**Comment by j-pb** [comment]
Ah, yeah sorry, my bad, we misread the percentages in respect to absolute time spend :)

**Comment by ptaoussanis** [comment]
No problem!
